### ISSUE TITLE
Feture Request: Multiselect Edit

### ISSUE THREAD

**Issue by adabru** [BlueSilverCat/edit-numbers#2]
Hi BlueSilverCat,

many thanks to this Atom-plugin, it simplifies my current task. If don't neglect feature requests, here is one:

When I have selected some Numbers via multiselect, I'd like to be able to modify the numbers with "editAll". At the moment only the last selected number is modified.

Example (from UltraStar):

```
: 0 2 ab
: 2 4 cd
- 6
: 6 4 ef
: 10 2 gh
``` 

Say I want to increase the time of the three last lines by 4 and change it to

```
: 0 2 ab
: 2 4 cd
- 10
: 10 4 ef
: 14 2 gh
``` 

My current procedure:

- select last three lines
- editAll with modifier "add 4" and prefix `: `
- editAll with modifier "add 4" and prefix `- `

My wished procedure:

- multiselect the 3 numbers via:
  - cursor before `- 10`
  - add 2 cursors to the bottom
  - 2 x arrow-right
  - shift+ctrl+arrow-right
- editAll with modifier "add 4"

**Comment by BlueSilverCat** [comment]
I'm sorry I could not respond.
I think that it has already been resolved, but it can be solved with current version.

you use Regular expression for that purpose.
for example.

- select last three lines.
- set "modify" to editType, set "0" to start, and set "4" to add.
- set "[-:]."(not include quotation) to prefix. 
- push editAll
